name: .NET deploy

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: app/out
    - name: Zip build files
      run: |
          cd app/out
          zip -r buildfiles.zip . -x '*.git*'
          ls
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cicddotnetcore
        environment_name: cicddotnetcore-prod
        version_label: ${{ GITHUB.run_id }}
        region: ap-south-1
        deployment_package: app/out/buildfiles.zip
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{secrets.WEBHOOK_URL}}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        dry_run: False