name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: | 
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact-Master
        path: /home/runner/work/ci-cd-dotnet-core/ci-cd-dotnet-core/ci-cd-dotnet-core/bin/Debug/netcoreapp3.1/publish/
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: Artifact-Master
    - name: Zip Artifact
      shell: cmd
      run: |
          7z a -tzip Artifact-Master.zip ./
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cicddotnetcore
        environment_name: cicddotnetcore-prod
        version_label: 12345
        region: ap-south-1
        deployment_package: Artifact-Master.zip