name: .NET

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: | 
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: |
          dotnet publish --configuration Release -o 'app/out'
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: app/out
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
    - name: Zip build files
      run: |
          zip -r buildfiles.zip . -x '*.git*'
          ls
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cicddotnetcore
        environment_name: cicddotnetcore-prod
        version_label: ${{ GITHUB.run_id }}
        region: ap-south-1
        deployment_package: app/out/buildfiles.zip
    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{secrets.WEBHOOK_URL}}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        dry_run: False